config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'links#index'
  resources :links

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, presence: true
  validates :title, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
before_filter :authenticate_user!, except: [:index, :show]
  def index
    @links = Link.all
  end

  def new
    @link = current_user.links.build
  end

  def create
    @link = current_user.links.build(link_params)
    if @link.save
      flash[:notice] = "You have created a new link."
      redirect_to action: :index
    else
      flash[:alert] = "You done messed up bad."
      render :new
    end
  end

  def show

  end

  def destroy
    @link = Link.find(params[:id])
    @link.delete
    redirect_to action: :index
  end

private
  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>

  <% if user_signed_in? %>
    <ul>
      <li><%= link_to "Submit Link", new_link_path %></li>
      <li><%= link_to "Account", edit_user_registration_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path %></li>
    </ul>
    <% else %>
    <ul>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    </ul>
  <% end %>
<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
edit.html.erb

app/views/links/index.html.erb
<h1> Listing Links </h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.url %></td>
        <td><%= link_to 'Show', link %></td>
        <% if link.user == current_user %>
          <td><%= link_to 'Edit', edit_link_path(link) %></td>
          <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1> New Link </h1>
<%= form_for @link, url: links_path do |f| %>
<p> Title </p>
<%= f.text_field :title %>
<p> Url </p>
<%= f.text_field :url %>
<br />
<%= f.submit "Create Link" %>
<% end %>

<%= link_to("Home", links_path) %>